services:
  - type: web
    name: lakshmi-ai-wife
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    region: oregon
    plan: free
